name: 'Update list of analysis and deploy'

on:
  push:
    branches:
    - main

permissions:
  contents: write
  pages: write
  id-token: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  update_script:
    name: run script
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10' 
          cache: 'pip' # caching pip dependencies

      - run: pip install -r requirements.txt

      - name: Run update script
        run: ./update_index.py

      - name: Update changed files
        uses: stefanzweifel/git-auto-commit-action@v4

  deploy:
    needs: update_script
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
